add deliver test

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -19,7 +19,79 @@ app:
   - BITFALL_APPSTORECONNECT_API_KEY_ISSUER_ID: $BITFALL_APPSTORECONNECT_API_KEY_ISSUER_ID
 
 workflows:
-  test_api_key_connection_auth:
+  test_deliver:
+    envs:
+    - TEST_APP_URL: https://github.com/bitrise-io/sample-apps-itunes-connect-beta-test.git
+    - TEST_APP_BRANCH: update
+    - BITRISE_PROJECT_PATH: ./Bitrise-iTunesConnectBetaTest/Bitrise-iTunesConnectBetaTest.xcodeproj
+    - BITRISE_SCHEME: Bitrise-iTunesConnectBetaTest
+    - INFO_PLIST_PATH: ./Bitrise-iTunesConnectBetaTest/Bitrise-iTunesConnectBetaTest/Info.plist
+    steps:
+    - change-workdir:
+        inputs:
+        - path: ./_tmp
+    - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git:
+        inputs:
+        - repository_url: $TEST_APP_URL
+        - branch: $TEST_APP_BRANCH
+        - clone_into_dir: .
+    - manage-ios-code-signing:
+        inputs:
+        - distribution_method: app-store
+        - scheme: $BITRISE_SCHEME
+        - certificate_url_list: $BITFALL_APPLE_APPLE_CERTIFICATE_URL_LIST|$BITFALL_APPLE_IOS_CERTIFICATE_URL_LIST
+        - passphrase_list: $BITFALL_APPLE_APPLE_CERTIFICATE_PASSPHRASE_LIST|$BITFALL_APPLE_IOS_CERTIFICATE_PASSPHRASE_LIST
+        - keychain_path: $BITRISE_KEYCHAIN_PATH
+        - keychain_password: $BITRISE_KEYCHAIN_PASSWORD
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            CURRENT_BUILD_NUMBER=${BITRISE_BUILD_NUMBER}
+            BITRISE_BUILD_NUMBER=$((($(gdate +%Y%m%d%H%M%S)-20000000000000)*10000))
+            if [[ -z "${BITRISE_BUILD_NUMBER}" ]]; then
+              echo "error: failed to calculated build number"
+              exit 1
+            fi
+            if [[ -n "${CURRENT_BUILD_NUMBER}" ]]; then
+              BITRISE_BUILD_NUMBER=$((${BITRISE_BUILD_NUMBER}+${CURRENT_BUILD_NUMBER}))
+            fi
+
+            envman add --key BITRISE_BUILD_NUMBER --value "${BITRISE_BUILD_NUMBER}"
+    - set-xcode-build-number:
+        title: Set Build Number
+        inputs:
+        - build_short_version_string: "4.1"
+        - build_version: $BITRISE_BUILD_NUMBER
+        - plist_path: $INFO_PLIST_PATH
+        - build_version_offset: $BITRISE_BUILD_VERSION_OFFSET
+    - xcode-archive:
+        title: Create Archive
+        inputs:
+        - output_dir: $BITRISE_DEPLOY_DIR
+        - project_path: $BITRISE_PROJECT_PATH
+        - distribution_method: app-store
+    - path::./:
+        inputs:
+        - connection: automatic
+        - altool_options: --output-format xml
+    # - path::./:
+    #     inputs:
+    #     - connection: $CONNECTION
+    #     - itunescon_user: $ITUNESCON_USER
+    #     - password: $ITUNESCON_PASSWORD
+    #     - api_key_path: $API_KEY_URL
+    #     - api_issuer: $API_KEY_ISSUER
+    #     - app_password: $APP_SPECIFIC_PASSWORD
+    #     - team_id: $TEAM_ID
+    #     - app_id: $APP_ID
+    #     - skip_screenshots: "no"
+    #     - skip_metadata: "yes"
+    #     - submit_for_review: "no"
+    #     - fastlane_version: latest
+    #     - verbose_log: "yes"
+
+  man_test_api_key_connection_auth:
     title: Test API key connection authentication
     before_run:
     - _prepare_test
